package com.practice2308.demo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity // to assign that this class is used to connected to the database
@Table(name = "login") // this the name of the table in the database
public class Student {

	// define the field

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // this show that id is auto generated by the database
	@Column(name = "id")
	private int id;

	@Column(name = "uemail")
	private String email;

	@Column(name = "upwd")
	private String upwd;

	// define the constructor

	public Student() {

	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUpwd() {
		return upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public Student(int id, String email, String upwd) {
		super();
		this.id = id;
		this.email = email;
		this.upwd = upwd;
	}

	
	
	public Student(String email, String upwd) {
		super();
		this.email = email;
		this.upwd = upwd;
	}

	@Override
	public String toString() {
		return "Student [id=" + id + ", email=" + email + ", upwd=" + upwd + "]";
	}
//
//@Entity // to assign that this class is used to connected to the database
//@Table(name = "student") // this the name of the table in the database
//public class Student {
//
//	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//	@Column(name = "id")
//	private int id;
//
//	@Column(name = "first_name")
//	private String firstName;
//
//	@Column(name = "last_name")
//	private String lastName;
//
//	@Column(name = "email")
//	private String email;
//
//	public Student(int id, String firstName, String lastName, String email) {
//		super();
//		this.id = id;
//		this.firstName = firstName;
//		this.lastName = lastName;
//		this.email = email;
//	}
//
//	public Student() {
//		super();
//	}
//
//	public int getId() {
//		return id;
//	}
//
//	public void setId(int id) {
//		this.id = id;
//	}
//
//	public String getFirstName() {
//		return firstName;
//	}
//
//	public void setFirstName(String firstName) {
//		this.firstName = firstName;
//	}
//
//	public String getLastName() {
//		return lastName;
//	}
//
//	public void setLastName(String lastName) {
//		this.lastName = lastName;
//	}
//
//	public String getEmail() {
//		return email;
//	}
//
//	public void setEmail(String email) {
//		this.email = email;
//	}
//
//	@Override
//	public String toString() {
//		return "Student [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", email=" + email + "]";
//	}

}
